#!/bin/zsh

# Aliases
alias e="emacsclient -ca ''"
alias matlab="matlab -nodesktop -nosplash"
alias stow="stow --dotfiles"

alias gs="git status"
alias gc="git commit"
alias gd="git diff"
alias ga="git add"

alias df="df -h"
alias du="du -h"
alias free="free -h"

alias ls="ls --color --dereference-command-line"
alias l='ls -lah'
alias ..="cd .."
alias '~'="cd ~"

alias svg="feh -x --reload 1 --conversion-timeout 1"
alias md2pdf="pandoc -V geometry:margin=1in --pdf-engine=xelatex --variable mainfont=Helvetica -t pdf -f gfm -i"

if $(hash xdg-open 2>/dev/null); then
    alias open="xdg-open"
fi

if $(hash guix 2>/dev/null); then
    alias gpu="guix_profile --update"
    alias gpi="guix_profile --install"
    alias gpr="guix_profile --remove"
    alias gpe="guix_profile --export-manifest"
fi

compctl -g '*.md' md2pdf
compctl -g '*.ppt*' pptx2pdf
compctl -g '*.docx' docx2pdf

# Plugins
plugins=(
    zsh-users/zsh-completions
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-autosuggestions
    hlissner/zsh-autopair
    ael-code/zsh-colored-man-pages
    jeffreytse/zsh-vi-mode
    omz/pip
    # omz/pass
    # omz/ripgrep
    # omz/zsh-pandoc-completion
    omz/fzf@delay
    Aloxaf/fzf-tab@delay
)

source $ZDOTDIR/plugins.zsh

# Set vi bindings and add custom key bindings
zvm_after_lazy_keybindings() {
    # bindkey -v
    bindkey -a k history-beginning-search-backward
    bindkey -a j history-beginning-search-forward
    bindkey -a H vi-beginning-of-line
    bindkey -a L vi-end-of-line
    bindkey -r -a v
}
bindkey -v '^@' fzf-tab-complete #^@ is <C-Space>
bindkey -v '^F' forward-char
bindkey -v '^P' history-beginning-search-backward
bindkey -v '^N' history-beginning-search-forward
bindkey -v '^R' fzf

export KEYTIMEOUT=1

# Change cursor based on vi-mode
zvm_after_select_vi_mode () {
    if [ $ZVM_MODE = $ZVM_MODE_INSERT ]; then
        echo -ne "\e[5 q"
    else
        echo -ne "\e[2 q"
    fi
}
ZVM_CURSOR_STYLE_ENABLED=false

# Prompt
fpath=("$ZDOTDIR" $fpath)
autoload -Uz prompt.zsh; prompt.zsh

# Directories
setopt AUTO_PUSHD
setopt PUSHD_SILENT
alias d="dirs -v"
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# plugins=(
#     vi-mode
#     pass
#     pip
#     ripgrep
#     zsh-pandoc-completion
#     colorize
#     docker
# )

# Completion
autoload -Uz compinit; compinit
_comp_options+=(globdots)
source "$ZDOTDIR/completion.zsh"
