#!/bin/zsh

# Aliases
alias e="emacsclient -ca ''"
alias vi="nvim"
alias stow="stow --dotfiles"

alias gs="git status"
alias gc="git commit"
alias gd="git diff"
alias ga="git add"

alias df="df -h"
alias du="du -h"
alias free="free -h"

alias ls="ls --color --dereference-command-line"
alias l='ls -lah'
alias ..="cd .."
alias '~'="cd ~"

alias svg="feh -x --reload 1 --conversion-timeout 1"
alias md2pdf="pandoc -V geometry:margin=1in --pdf-engine=xelatex --variable mainfont=Helvetica -t pdf -f gfm -i"

if $(hash xdg-open 2>/dev/null); then
    alias open="xdg-open"
fi

compctl -g '*.md' md2pdf
compctl -g '*.ppt*' pptx2pdf
compctl -g '*.docx' docx2pdf

# Plugins
# export FZF_BASE="$(fzf-share)"
# plugins=(
#     zsh-users/zsh-completions
#     zsh-users/zsh-syntax-highlighting
#     zsh-users/zsh-autosuggestions
#     # hlissner/zsh-autopair@delay
#     ael-code/zsh-colored-man-pages
#     jeffreytse/zsh-vi-mode
#     # omz:pip
#     omz:pass/_pass
#     omz:ripgrep/_ripgrep
#     srijanshetty/zsh-pandoc-completion
#     omz:fzf@delay
#     Aloxaf/fzf-tab@delay
# )

# source $ZDOTDIR/plugins.zsh

# Set vi bindings and add custom key bindings
zvm_after_lazy_keybindings() {
    bindkey -a k history-search-backward
    bindkey -a j history-search-forward
    bindkey -a H vi-beginning-of-line
    bindkey -a L vi-end-of-line
    bindkey -a / fzf-history-widget
    # \e works as meta.
    bindkey -v '\ep' history-search-backward
    bindkey -v '\en' history-search-forward
}
bindkey -v '^@' fzf-tab-complete # ^@ is <C-Space>.

export KEYTIMEOUT=1

# Change cursor based on vi-mode
zvm_after_select_vi_mode () {
    if [ $ZVM_MODE = $ZVM_MODE_INSERT ]; then
        echo -ne "\e[5 q"
    else
        echo -ne "\e[2 q"
    fi
}
ZVM_CURSOR_STYLE_ENABLED=false

# Prompt
fpath=("$ZDOTDIR" $fpath)
autoload -Uz prompt.zsh; prompt.zsh

# Window title
autoload -Uz add-zsh-hook

xterm_title_precmd () {
    print -Pn -- '\e]2;%~ \a'
}

xterm_title_preexec () {
    print -Pn -- "\\e\]2;${(q)1}: %~\a"
}

if [[ "$TERM" == alacritty* ]]; then
    add-zsh-hook -Uz precmd xterm_title_precmd
    add-zsh-hook -Uz preexec xterm_title_preexec
fi

# Directories
WORDCHARS=${WORDCHARS//[\/=]} # Remove "/" and "=" so they are not part of words
setopt AUTO_PUSHD
setopt PUSHD_SILENT
alias d="dirs -v"
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# Completion
autoload -Uz compinit; compinit
_comp_options+=(globdots)
source $ZDOTDIR/completion.zsh

eval "$(direnv hook zsh)"
