set -s escape-time 5
set -g status-style bg=white,fg=black

set-window-option -g mode-keys vi

bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key J swap-pane -D
bind-key K swap-pane -U
bind-key g set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"
bind-key = select-layout -E
