#!/bin/zsh

# ZSH files
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/zsh/history"
export HISTSIZE=10000
export SAVEHIST=10000

# Editors
export EDITOR="emacsclient -nw"
export VISUAL="emacsclient -ca ''"

export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export STOW_DIR="$HOME/.dotfiles"
