;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
 (list "emacs-use-package"
       "emacs-no-littering"
       "emacs-sly"
       "emacs-direnv"
       "emacs-git-gutter-fringe"
       "emacs-all-the-icons"
       "emacs-helm-selector"
       "emacs-helm-system-packages"
       "emacs-elfeed"
       "emacs-elfeed-org"
       "emacs-projectile"
       "emacs-counsel-projectile"
       "emacs-magit"
       "emacs-git-gutter"
       "emacs-git-timemachine"
       "emacs-general"
       "emacs-evil"
       "emacs-evil-collection"
       "emacs-evil-nerd-commenter"
       "emacs-evil-goggles"
       "emacs-evil-surround"
       "emacs-prescient"
       "emacs-ivy"
       "emacs-ivy-posframe"
       "emacs-ivy-rich"
       "emacs-counsel"
       "emacs-swiper"
       "emacs-amx"
       "emacs-company"
       "emacs-company-quickhelp"
       "emacs-company-box"
       "emacs-company-math"
       "emacs-yasnippet"
       "emacs-which-key"
       "emacs-avy"
       "emacs-evil-exchange"
       "emacs-ace-window"
       "emacs-evil-args"
       "emacs-evil-lion"
       "emacs-rainbow-delimiters"
       "emacs-undo-fu"
       "emacs-undo-fu-session"
       "emacs-undo-tree"
       "emacs-link-hint"
       "emacs-highlight-indent-guides"
       "emacs-dumb-jump"
       "emacs-iedit"
       "emacs-dired-hacks"
       "emacs-modus-themes"
       "emacs-visual-fill-column"
       "emacs-gcmh"
       "emacs-smartparens"
       "emacs-evil-smartparens"
       "emacs-flycheck"
       "emacs-refactor"
       "emacs-highlight-defined"
       "emacs-helpful"
       "emacs-elisp-demos"
       "emacs-geiser"
       "emacs-lispy"
       "emacs-lispyville"
       "emacs-polymode"
       "emacs-ess"
       "emacs-elpy"
       "emacs-pdf-tools"
       "emacs-guix"
       "emacs-org"
       "emacs-org-superstar"
       "emacs-evil-org"
       "emacs-ox-hugo"
       "emacs-org-roam"
       "emacs-org-roam-bibtex"
       "emacs-wordnut"
       "emacs-org-ref"
       "emacs-helm"
       "emacs-ebib"
       "emacs-deft"
       "emacs-flyspell-correct"
))

       ;; "emacs-eyebrowse"
       ;; "emacs-golden"
       ;; "emacs-evil-easymotion"
       ;; "emacs-org-msg"
       ;; "emacs-elisp-def"
       ;; "emacs-highlight-function-calls"
       ;; "emacs-format-all"
       ;; "emacs-org-cliplink"
       ;; "emacs-citeproc-org"
       ;; "emacs-org-roam-server"
       ;; "emacs-sdcv-mode"
       ;; "emacs-wiki-summary"
       ;; "emacs-bibtex"
